kind: Secret
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}
  annotations:
    avp.kubernetes.io/path: "{{ .Values.secretPath }}"
type: Opaque
data:
  FULL_FILE_NAME: <FULL_FILE_NAME | base64encode>
  DIRECTORY: <DIRECTORY | base64encode>
  FILE_NAME: <FILE_NAME | base64encode>
  CLOUDFLARE_ZONE_ID: <CLOUDFLARE_ZONE_ID | base64encode>
  CLOUDFLARE_DNS_RECORD_ID: <CLOUDFLARE_DNS_RECORD_ID | base64encode>
  CLOUDFLARE_BEARER_TOKEN: <CLOUDFLARE_BEARER_TOKEN | base64encode>
  CLOUDFLARE_RECORD_TYPE: <CLOUDFLARE_RECORD_TYPE | base64encode>
  CLOUDFLARE_RECORD_NAME: <CLOUDFLARE_RECORD_NAME | base64encode>
  CLOUDFLARE_ZONE_NAME: <CLOUDFLARE_ZONE_NAME | base64encode>
  CLOUDFLARE_RULE_PROXIED: <CLOUDFLARE_RULE_PROXIED | base64encode>
  CLOUDFLARE_RULE_TTL: <CLOUDFLARE_RULE_TTL | base64encode>
  CLOUDFLARE_RULE_LOCKED: <CLOUDFLARE_RULE_LOCKED | base64encode>
  CLOUDFLARE_RULE_PROXIABLE: <CLOUDFLARE_RULE_PROXIABLE | base64encode>
  CLOUDFLARE_RULE_AUTO_ADDED: <CLOUDFLARE_RULE_AUTO_ADDED | base64encode>
  CLOUDFLARE_RULE_MANAGED_BY_APPS: <CLOUDFLARE_RULE_MANAGED_BY_APPS | base64encode>
  CLOUDFLARE_RULE_MANAGED_BY_ARGO_TUNNEL: <CLOUDFLARE_RULE_MANAGED_BY_ARGO_TUNNEL | base64encode>
  SUPERALERT_BEARER_TOKEN: <SUPERALERT_BEARER_TOKEN | base64encode>
  